import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./header/page";
import Footer from "./footer/page";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        {/* Header cố định trên cùng (nếu cần) */}
        <Header />

        {/* Phần chính mở rộng tự động */}
        <main className="flex-1 w-[full]  ">{children}</main>

        {/* Footer luôn hiển thị */}
        <Footer />
      </body>
    </html>
  );
}
